[package]
name = "rustpython-compiler-core"
description = "RustPython specific bytecode."
version = "0.3.0"
authors = ["RustPython Team"]
edition = "2021"
repository = "https://github.com/RustPython/RustPython"
license = "MIT"

[dependencies]
rustpython-parser-core = { workspace = true, features=["location"] }

bitflags = { workspace = true }
itertools = { workspace = true }
malachite-bigint = { workspace = true }
num-complex = { workspace = true }
serde = { version = "1.0.133", optional = true, default-features = false, features = ["derive"] }

lz4_flex = "0.11"
