[package]
name = "rustpython"
version = "0.4.0"
description = "A Python-3 (CPython >= 3.5.0) Interpreter written in Rust ğŸ ğŸ˜± ğŸ¤˜"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/RustPython/RustPython"

[[module]]
name = "rustpython"
source = "target/wasm32-wasip1/release/rustpython.wasm"
abi = "wasi"

[[command]]
name = "rustpython"
module = "rustpython"

[fs]
"/lib/rustpython" = "Lib"
