[package]
name = "rustpython"
version = "0.1.3"
description = "A Python-3 (CPython >= 3.5.0) Interpreter written in Rust ğŸ ğŸ˜± ğŸ¤˜"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/RustPython/RustPython"

[[module]]
name = "rustpython"
source = "target/wasm32-wasi/release/rustpython.wasm"
abi = "wasi"
# interfaces = { wasi = "0.0.1-snapshot" }

[[command]]
name = "rustpython"
module = "rustpython"
