[package]
name = "rustpython_derive"
version = "0.1.0"
authors = ["Joey <jmhain@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.29", features = ["full"] }
quote = "0.6.11"
proc-macro2 = "0.4.27"
