[package]
name = "rustpython-derive"
version = "0.1.2"
description = "Rust language extensions and macros specific to rustpython."
authors = ["RustPython Team"]
repository = "https://github.com/RustPython/RustPython"
license = "MIT"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
rustpython-bytecode = { path = "../compiler/bytecode", version = "0.1.1" }
rustpython-codegen = { path = "../compiler/codegen", version = "0.1.1" }
rustpython-compiler = { path = "../compiler", version = "0.1.1" }
rustpython-doc = { git = "https://github.com/RustPython/__doc__", branch = "main" }

indexmap = "1.8.1"
itertools = "0.10.3"
maplit = "1.0.2"
once_cell = "1.10.0"
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn = { version = "1.0.91", features = ["full", "extra-traits"] }
syn-ext = { version = "0.4.0", features = ["full"] }
textwrap = { version = "0.15.0", default-features = false }
