[package]
name = "rustpython-sre_engine"
version = "0.3.1"
authors = ["Kangzhi Shi <shikangzhi@gmail.com>", "RustPython Team"]
description = "A low-level implementation of Python's SRE regex engine"
repository = "https://github.com/RustPython/RustPython"
license = "MIT"
edition = "2021"
keywords = ["regex"]
include = ["LICENSE", "src/**/*.rs"]

[dependencies]
num_enum = { workspace = true }
bitflags = { workspace = true }
optional = "0.5"
