[package]
name = "rustpython_parser"
version = "0.0.1"
authors = [ "Shing Lyu", "Windel Bouwman" ]
build = "build.rs"

[build-dependencies]
lalrpop="0.15.1"

[dependencies]
lalrpop-util="0.15.1"
log="0.4.1"
regex="0.2.2"
num-bigint = "0.2"
num-traits = "0.2"

