[package]
name = "rustpython-compiler-core"
version = "0.1.2"
description = "Compiler for python code into bytecode for the rustpython VM."
authors = ["RustPython Team"]
repository = "https://github.com/RustPython/RustPython"
license = "MIT"
edition = "2018"

[features]
std = ["rustpython-bytecode/std", "itertools/use_std"]
default = ["std"]

[dependencies]
indexmap = "1.0"
itertools = { version = "0.9", default-features = false }
rustpython-bytecode = { path = "../bytecode", version = "0.1.1", default-features = false }
rustpython-ast = { path = "../ast" }
num-complex = { version = "0.3", features = ["serde"] }
num-traits = "0.2"
log = "0.4"
ahash = "0.6"
scopeguard = "1.1"

[dev-dependencies]
rustpython-parser = { path = "../parser" }
insta = "1.1"
