[package]
name = "rustpython-derive-impl"
version = "0.2.0"
edition = "2021"

[dependencies]
rustpython-compiler-core = { path = "../compiler/core", version = "0.2.0" }
rustpython-doc = { git = "https://github.com/RustPython/__doc__", branch = "main" }

indexmap = "1.8.1"
itertools = "0.10.3"
maplit = "1.0.2"
once_cell = "1.10.0"
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn = { version = "1.0.91", features = ["full", "extra-traits"] }
syn-ext = { version = "0.4.0", features = ["full"] }
textwrap = { version = "0.15.0", default-features = false }
