[package]
name = "rustpython-derive-impl"
version = "0.3.0"
description = "Rust language extensions and macros specific to rustpython."
authors = ["RustPython Team"]
repository = "https://github.com/RustPython/RustPython"
license = "MIT"
edition = "2021"

[dependencies]
rustpython-compiler-core = { workspace = true }
rustpython-parser-core = { workspace = true }
rustpython-doc = { workspace = true }

itertools = { workspace = true }
once_cell = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }

maplit = "1.0.2"
proc-macro2 = "1.0.60"
quote = "1.0.18"
syn-ext = { version = "0.4.0", features = ["full"] }
textwrap = { version = "0.15.0", default-features = false }
