[package]
name = "rustpython-derive-impl"
version = "0.2.0"
edition = "2021"

[dependencies]
rustpython-compiler-core = { workspace = true }
rustpython-parser-core = { workspace = true }
rustpython-doc = { workspace = true }

indexmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }

maplit = "1.0.2"
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn-ext = { version = "0.4.0", features = ["full"] }
textwrap = { version = "0.15.0", default-features = false }
