on:
  push:
    branches: [gh-rel-rustpython]

name: Release

permissions:
  contents: write

env:
  CARGO_ARGS: --no-default-features --features stdlib,zlib,importlib,encodings,sqlite,ssl

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
#          - runner: ubuntu-latest
#            target: i686-unknown-linux-gnu
#          - runner: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
#          - runner: ubuntu-latest
#            target: armv7-unknown-linux-gnueabi
#          - runner: ubuntu-latest
#            target: s390x-unknown-linux-gnu
#          - runner: ubuntu-latest
#            target: powerpc64le-unknown-linux-gnu
          - runner: macos-latest
            target: aarch64-apple-darwin
#          - runner: macos-latest
#            target: x86_64-apple-darwin
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
#          - runner: windows-latest
#            target: i686-pc-windows-msvc
#          - runner: windows-latest
#            target: aarch64-pc-windows-msvc
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Set up Environment
        shell: bash
        run: rustup target add ${{ matrix.platform.target }}
      - name: Set up Windows Environment
        shell: bash
        run: |
          cargo install --target-dir=target -v cargo-vcpkg
          cargo vcpkg -v build
        if: runner.os == 'Windows'
      - name: Set up MacOS Environment
        run: brew install autoconf automake libtool
        if: runner.os == 'macOS'

      - name: Build RustPython
        run: cargo build --release --target=${{ matrix.platform.target }} --verbose --features=threading ${{ env.CARGO_ARGS }}
        if: runner.os == 'macOS'
      - name: Build RustPython
        run: cargo build --release --target=${{ matrix.platform.target }} --verbose --features=threading ${{ env.CARGO_ARGS }},jit
        if: runner.os != 'macOS'

      - name: Rename Binary
        run: cp target/${{ matrix.platform.target }}/release/rustpython target/rustpython-release-${{ runner.os }}-${{ matrix.platform.target }}
        if: runner.os != 'Windows'
      - name: Rename Binary
        run: cp target/${{ matrix.platform.target }}/release/rustpython.exe target/rustpython-release-${{ runner.os }}-${{ matrix.platform.target }}
        if: runner.os == 'Windows'

      - name: Upload Binary Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustpython-release-${{ runner.os }}-${{ matrix.platform.target }}
          path: target/rustpython-release-${{ runner.os }}-${{ matrix.platform.target }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Binary Artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin
          pattern: rustpython-release-*
          merge-multiple: true

      - name: List Binaries
        run: |
          ls -lah bin/
          file bin/*
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          run: ${{ github.run_number }}
        run: |
          today=$(date '+%Y-%m-%d')
          gh release create "$today-$tag-$run" \
              --repo="$GITHUB_REPOSITORY" \
              --title="RustPython Release $today-$tag #$run" \
              --generate-notes \
              bin/rustpython-release-*