[package]
name = "rustpython-pylib"
description = "A subset of the Python standard library for use with RustPython"
license-file = "Lib/PSF-LICENSE"
include = ["Cargo.toml", "src/**/*.rs", "Lib/", "!Lib/**/test/", "!Lib/**/*.pyc"]
authors = ["CPython Developers"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[features]
freeze-stdlib = ["dep:rustpython-compiler-core", "dep:rustpython-derive"]

[dependencies]
rustpython-compiler-core = { workspace = true, optional = true }
rustpython-derive = { workspace = true, optional = true }

[build-dependencies]
glob = { workspace = true }

[lints]
workspace = true
